name: mavenbuild
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v4
     - name: Set up JDK 17
       uses: actions/setup-java@v3
       with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
     - name: Build with maven
       run: | 
            mvn -B package --file pom.xml


  job2:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v4
     - name: Set up JDK 17
       uses: actions/setup-java@v3
       with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
     - name: Build with maven
       run: | 
            mvn -B install --file pom.xml

  
